networking_poe_ssl_certs_0_certificate: ((pas_network_cert.certificate))
networking_poe_ssl_certs_0_name: router-cert
networking_poe_ssl_certs_0_privatekey: ((pas_network_cert.private_key))

# Just use the same cert for UAA
# uaa_service_provider_key_credentials_certificate: ((uaa_service_provider_key_credentials.certificate))
# uaa_service_provider_key_credentials_privatekey: ((uaa_service_provider_key_credentials.private_key))
uaa_service_provider_key_credentials_certificate: ((pas_network_cert.certificate))
uaa_service_provider_key_credentials_privatekey: ((pas_network_cert.private_key))

credhub_internal_provider_keys_0_key: ((credhub_internal_provider_keys_0_key))
credhub_internal_provider_keys_0_name: ((credhub_internal_provider_keys_0_name))
credhub_internal_provider_keys_0_primary: true
