---
pivnet-api-token: ((pivnet-api-token))
pivnet-file-glob: "*-azure-*"
pivnet-product-slug: "stemcells-ubuntu-xenial"
product-version: "621.75"

# Use these vars when pulling from azure blobstore
# azure-storage-account: telmoreprodandstemcell
# azure-storage-key: ((azure-storage-key))
# blobstore-bucket: productstorage