singleton_availability_zone: az1
az2_name: az2
az3_name: az3
cloud_controller_apps_domain: apps.lab01.lab.telmore.io
cloud_controller_system_domain: sys.lab01.lab.telmore.io
enable_smb_volume_driver: false
router_static_ips: 10.1.20.20,10.1.20.21,10.1.20.22

# enable_log_cache_syslog_ingestion: true

# resource-var-diego_brain_instances: 1
resource-var-router_instances: 2
resource-var-router_additional_vm_extensions: ["tas_gorouter_vm_extension"]
# resource-var-diego_cell_instances: 3
resource-var-diego_brain_additional_vm_extensions: ["tas_ssh_vm_extension"]
resource-var-tcp_router_additional_vm_extensions: ["tas_tcp_vm_extension"]