singleton_availability_zone: zone-1
az2_name: zone-2
az3_name: zone-3
network_name: pks5
service_network_name: services
pks_api_hostname: api.pks.sbx.my3votes.com

plan1_selector_active_master_az_placement: ["zone-1"]
plan1_selector_active_worker_az_placement: ["zone-1","zone-2","zone-3"]

cloud_provider_azure_azure_cloud_name: AzurePublicCloud
cloud_provider_azure_azure_master_managed_identity: sbx-pks-master
cloud_provider_azure_azure_worker_managed_identity: sbx-pks-worker
cloud_provider_azure_default_security_group: sbx-pks-api-network-sgs
cloud_provider_azure_disable_outbound_snat: false
cloud_provider_azure_location: eastus
cloud_provider_azure_primary_availability_set: sbx-pks-as
cloud_provider_azure_resource_group_name: sbx
cloud_provider_azure_vnet_name: sbx-platform
cloud_provider_azure_vnet_resource_group_name: sbx
resource-var-pivotal-container-service_elb_names: "sbx-pks-lb"

upgrade-all-service-instances_post_deploy_state: false
smoke-tests_post_deploy_state: false