concurrent_service_instance_upgrade: 5
config_server_access: global
config_server_credhub_enabled: true
java_buildpack: java_buildpack_offline
service_completion_timeout_minutes: 30
service_key_access: false
service_registry_access: global
syslog_address: null
syslog_custom_rsyslog_configuration: ""
syslog_enabled: false
syslog_forward_debug_logs: false
syslog_permitted_peer: false
syslog_port: null
syslog_queue_size: 100000
syslog_ssl_ca_certificate: null
syslog_tls_enabled: false
syslog_transport_protocol: tcp
destroy-brokers_pre_delete_state: default
register-brokers_post_deploy_state: default
upgrade-all-instances_post_deploy_state: default
resource-var-spring-cloud-services_instance_type: automatic
resource-var-spring-cloud-services_max_in_flight: default
resource-var-spring-cloud-services_persistent_disk_size: automatic
